import * as vscode from 'vscode';
export declare class FileWatcher {
    private patternDetector;
    private notificationManager;
    private qualityAnalyzer;
    private interventionEngine;
    private outputChannel;
    private fileAnalysisHistory;
    private detectionCount;
    private aiInterventionCount;
    private typingTimer;
    private lastAnalysisTime;
    private isAnalyzing;
    private readonly TYPING_DELAY;
    private readonly MIN_ANALYSIS_INTERVAL;
    constructor(outputChannel: vscode.OutputChannel);
    startMonitoring(): vscode.Disposable[];
    private handleTextChange;
    private handlePreSave;
    private handleFileSave;
    private handleFileFocus;
    private performRealtimeAnalysis;
    private analyzeDocument;
    private handleQualityDetection;
    private requestAIFixes;
    private analyzeCurrentFile;
    private showDetailedQualityReport;
    private isCodeFile;
    private determineInterventionLevel;
    private storeAnalysisHistory;
    private queueWarningNotification;
    getStats(): any;
    dispose(): void;
}
