"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CORRECTION_PROMPT_DELAY = exports.INTERVENTION_COOLDOWN = exports.MEDIUM_SEVERITY_PATTERN_SCORE = exports.SCOPE_REDUCTION_SCORE = exports.AVOIDANCE_WORD_SCORE = exports.HIGH_SEVERITY_PATTERN_SCORE = exports.CONVERSATION_ANALYSIS_DELAY = exports.RECENT_ANALYSES_TIMESPAN = exports.INTERVENTION_LOCK_RELEASE_DELAY = exports.TERMINAL_CORRECTION_DELAY = exports.AUTO_INTERVENTION_SCORE_THRESHOLD = exports.WARNING_INTERVENTION_THRESHOLD = exports.CORRECT_INTERVENTION_THRESHOLD = exports.MAX_ANALYSIS_HISTORY = exports.FOCUS_ANALYSIS_DELAY = void 0;
exports.FOCUS_ANALYSIS_DELAY = 500;
exports.MAX_ANALYSIS_HISTORY = 10;
exports.CORRECT_INTERVENTION_THRESHOLD = 25;
exports.WARNING_INTERVENTION_THRESHOLD = 10;
exports.AUTO_INTERVENTION_SCORE_THRESHOLD = 30;
exports.TERMINAL_CORRECTION_DELAY = 1000;
exports.INTERVENTION_LOCK_RELEASE_DELAY = 5000;
exports.RECENT_ANALYSES_TIMESPAN = 3600000;
exports.CONVERSATION_ANALYSIS_DELAY = 1000;
exports.HIGH_SEVERITY_PATTERN_SCORE = 10;
exports.AVOIDANCE_WORD_SCORE = 8;
exports.SCOPE_REDUCTION_SCORE = 12;
exports.MEDIUM_SEVERITY_PATTERN_SCORE = 5;
exports.INTERVENTION_COOLDOWN = 30000;
exports.CORRECTION_PROMPT_DELAY = 1500;
//# sourceMappingURL=constants.js.map