export const FOCUS_ANALYSIS_DELAY = 500;
export const MAX_ANALYSIS_HISTORY = 10;
export const CORRECT_INTERVENTION_THRESHOLD = 25;
export const WARNING_INTERVENTION_THRESHOLD = 10;
export const AUTO_INTERVENTION_SCORE_THRESHOLD = 30;
export const TERMINAL_CORRECTION_DELAY = 1000;
export const INTERVENTION_LOCK_RELEASE_DELAY = 5000;
export const RECENT_ANALYSES_TIMESPAN = 3600000;

export const CONVERSATION_ANALYSIS_DELAY = 1000;
export const HIGH_SEVERITY_PATTERN_SCORE = 10;
export const AVOIDANCE_WORD_SCORE = 8;
export const SCOPE_REDUCTION_SCORE = 12;
export const MEDIUM_SEVERITY_PATTERN_SCORE = 5;
export const INTERVENTION_COOLDOWN = 30000;
export const CORRECTION_PROMPT_DELAY = 1500;
